sudo: false
language: elixir

matrix:
  include:
    - otp_release: 22.3
      elixir: 1.10
    - otp_release: 21.3
      elixir: 1.8
    - otp_release: 21.3
      elixir: 1.7
    - otp_release: 20.3
      elixir: 1.6
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 19.0
      elixir: 1.4

env:
  - MIX_ENV=test

script:
  - mix test --trace
